// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANpyJOVaSaGuFwjhyN6I35uIyfgFzK6Ls',
    appId: '1:74534637147:web:778b565a31000b7c70f97e',
    messagingSenderId: '74534637147',
    projectId: 'shcedule04',
    authDomain: 'shcedule04.firebaseapp.com',
    storageBucket: 'shcedule04.firebasestorage.app',
    measurementId: 'G-D534D8TFK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBk4vbk5Cgjc2Vz1kPUt1acdfqJN88Atc',
    appId: '1:74534637147:android:2ec20cac5d86a2e370f97e',
    messagingSenderId: '74534637147',
    projectId: 'shcedule04',
    storageBucket: 'shcedule04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Dsdj8jOeNY2k4OJy5vPNLfbEwS30Fkw',
    appId: '1:74534637147:ios:02b630911e50c94c70f97e',
    messagingSenderId: '74534637147',
    projectId: 'shcedule04',
    storageBucket: 'shcedule04.firebasestorage.app',
    iosBundleId: 'com.example.schedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Dsdj8jOeNY2k4OJy5vPNLfbEwS30Fkw',
    appId: '1:74534637147:ios:02b630911e50c94c70f97e',
    messagingSenderId: '74534637147',
    projectId: 'shcedule04',
    storageBucket: 'shcedule04.firebasestorage.app',
    iosBundleId: 'com.example.schedule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANpyJOVaSaGuFwjhyN6I35uIyfgFzK6Ls',
    appId: '1:74534637147:web:f83c12ac478c401270f97e',
    messagingSenderId: '74534637147',
    projectId: 'shcedule04',
    authDomain: 'shcedule04.firebaseapp.com',
    storageBucket: 'shcedule04.firebasestorage.app',
    measurementId: 'G-X36XE2B4Z1',
  );
}
